version: "2.2"
services:
  flask:
    container_name: "web"
    image: nxgcloud/om-web:0.0.1
    build: ./flask
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy 
    command: ["/bin/sh", "-c", "/emarket/startup.sh"]
  mysql:
    container_name: "db"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Welcome"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "naresh"
      MYSQL_PASSWORD: "Welcome"
    healthcheck:
      test: "/usr/bin/mysql --user=naresh --password=Welcome --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 1s
      retries: 5
    ports: 
      - "3306:3306"
  redis:
    container_name: "redis"    
    image: redis:3.2.11
    ports: 
      - "6379:6379"