version: "2.2"
services:
  flask:
    container_name: "flaskc02"
    build: flask
    command:
      - /bin/sh
      - -c
      - /emarket/startup.sh
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy 
  mysql:
    image: mysql:5.7
    container_name: "dbc02"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Welcome"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "naresh"
      MYSQL_PASSWORD: "Welcome"
    healthcheck:
      test: "/usr/bin/mysql --user=naresh --password=Welcome --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 1s
      retries: 5
  redis:
    image: redis:3.2.11
    container_name: "redisc02"
    ports: 
      - "6379:6379"