version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: "dbc02"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Welcome"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "naresh"
      MYSQL_PASSWORD: "Welcome"